version: 2
updates:
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /crawler
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
