services:
  s3:
    image: minio/minio
    environment:
      MINIO_DOMAIN: s3
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./s3:/data
    networks:
      s3:
        aliases:
          - assets.wor.jp.s3
    command: minio server /data --console-address :9001
  createbuckets:
    image: minio/mc
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - s3
    networks:
      - s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://s3:9000 minioadmin minioadmin) do echo 'Waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/assets.wor.jp;
      /usr/bin/mc policy set public minio/assets.wor.jp;
      exit 0;
      "
  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ./admin:/opt/project:cached
  crawler:
    build:
      context: crawler
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      RAILS_ENV: development
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - '8080:8080'
    volumes:
      - ./crawler:/var/task:cached
      - bundle:/var/task/vendor/bundle
    depends_on:
      - s3
    networks:
      - s3
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/opt/project:cached
volumes:
  bin:
  bundle:
networks:
  s3:
