# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gem 'rails', '~> 8.0.2.1'

gem 'aws-sdk-s3'
gem 'capybara', require: false
gem 'nkf', require: false
gem 'selenium-webdriver', require: false
gem 'sentry-rails'
gem 'sentry-ruby'

group :development, :test do
  gem 'rspec-rails'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'simplecov', require: false
end
