# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.6'

gem 'rails', '~> 7.0.3'

gem 'aws-sdk-s3'
gem 'capybara', require: false
gem 'selenium-webdriver', '< 4.0.0', require: false
gem 'sentry-rails'
gem 'sentry-ruby'

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end
