# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.7'

gem 'rails', '~> 7.0.5'

gem 'aws-sdk-s3'
gem 'capybara', require: false
gem 'selenium-webdriver', '< 4.0.0', require: false
gem 'sentry-rails'
gem 'sentry-ruby'

group :development, :test do
  gem 'rspec-rails'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'simplecov', require: false
end
