service: rsslovers-crawler

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-northeast-1
  timeout: 900
  environment:
    RAILS_MASTER_KEY: ${ssm:/rsslovers/rails_master_key}
  ecr:
    images:
      latest:
        path: ./

functions:
  main:
    image:
      name: latest
    events:
      - schedule: cron(10 * * * ? *)
