name: Admin CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'admin/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./admin

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install packages
        run: npm install

      - name: Run ESLint
        run: npx eslint app/**/*.ts
