name: Crawler CD

on:
  push:
    branches:
      - main
    paths:
      - 'crawler/**'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crawler

    steps:
      - uses: actions/checkout@v5

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/RSSLoversRole
          aws-region: ap-northeast-1

      - uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda
        env:
          DOCKER_BUILDKIT: 1
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls deploy
