name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Install packages
        run: npm install

      - name: Run ESLint
        run: npm run lint
